name = "ebg-rp-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
SP_SITE = "endlerbau.sharepoint.com"
SP_SITE_PATH = "/sites/EndlerBauDateien"

# Secrets (set via `wrangler secret put`):
# TENANT_ID
# CLIENT_ID
# CLIENT_SECRET
